server:
  port: 8081

gasAnalyser:
  portName: "/dev/ttyUSB1"
  baudRate:        9600
	dataBits:        8
	stopBits:        1
	minimumReadSize: 5
	parityMode:      0
	interCharacterTimeout: 10000

flowController:
  portName: "/dev/ttyUSB0"
	baudRate:        19200
	dataBits:        8
	stopBits:        1
	minimumReadSize: 5
	parityMode:      0
	interCharacterTimeout: 1

fcID1: 0x02
fcID2: 0x03